---

- name: set boundary_iface
  when: boundary_iface is undefined
  set_fact:
    boundary_iface: "{{ ansible_default_ipv4.interface }}"

- name: set boundary_address
  set_fact:
    boundary_address: "{{ hostvars[inventory_hostname]['ansible_'+boundary_iface]['ipv4']['address'] }}"

- name: collect facts about system services
  service_facts:
  register: services_state

- name: configure firewall
  include: firewall.yml

- name: install Boundary with Debian packages
  include: install_package_debian.yml
  when: ansible_os_family == 'Debian' and boundary_install_package == true

- name: install Boundary with RedHat packages
  include: install_package_redhat.yml
  when: ansible_os_family == 'RedHat' and boundary_install_package == true

- name: install Boundary manually
  include: install_manual.yml
  when:  boundary_install_package != true or ansible_os_family not in ['Debian', 'RedHat']

- name: install tls
  when: boundary_kms_type == 'transit'
  include_tasks: tls.yml

- name: configure boundary
  include: boundary_config.yml

- name: install boundary autocomplete
  include: autocomplete.yml
